name: PR Workflow - run tests
on:
  pull_request:
    types: opened
    branches:
      - main
jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Give gradlew permissions
        run: chmod +x gradlew
      - name: Run unit tests with Gradle
        run: ./gradlew testDebugUnitTest --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html